### PR TITLE
[Impl] Pointer Type Variant

### PR DESCRIPTION
**Pull request by curin**
## Table of Contents

* [Code of Conduct](#code-of-conduct)
* [Proposal Implementation](#proposal-implementation)

### Code of Conduct

This project has adopted the code of conduct defined by the [Contributor Covenant](http://contributor-covenant.org/) 
to clarify expected behavior in our community. For more information, see the [.NET Foundation Code of Conduct](http://www.dotnetfoundation.org/code-of-conduct).

## Proposal Implementation

[Impl] Pointer Type Variant
This implements a variant of the pointer objects which use generic syntax PtrRef<type, basetype> where type is any unmanaged types and basetype is meant as the interior most pointer. This is used to allow for PtrRef<Ptr<char, char>, char> still being able to cast to char**. The Pointer types can also look up the depth of the pointer types involved so PtrRef<Ptr<char, char>, char>.Depth == 2, and casts internally check this depth to ensure safe casting.

The PtrRef and PtrRefToConst are the old Mut and Ptr respectively. which then use the new Ptr and PtrToConst to store more complex pointer chains. The ref structs are the outermost layer to allow fixing when possible, but we already have to pin when handling multidimensional array objects so the non-ref structs handle these types just fine.

There are two type variants and generic and non-generic versions of each. Ptr is a standard pointer to a mutable object. PtrToConst is a pointer to an immutable object. While currently I don't think we have enough info in generation stage, you can take byte*const* and convert it to PtrToConst<Ptr<byte, byte>, byte> allowing you to have the same access to data as you would in C++.
 
These types have been tested against all Unit tests available and generated respective GLFW code.

### CODE REVIEW

**Comment by Perksey** [comment]
Btw, bit of a long shot, but do you know anything about GitHub Actions permissions? I get for security reasons CI jobs on forks are granted minimal permissions, but at the same time I'd quite like the test reports to be posted as a check run :/

Will review now.

**Comment by Perksey** [comment]
> These types do require a calling convention of being disposed if they are holding a managed object as they keep a pinned GCHandle. The assumption within the generated functions currently is that any Pointer type passed in is either unmanaged or an implicit cast and is disposed at the end of the function. Unmanaged Pointers used in Ptr objects are unaffected by Dispose.

Oh, I think for an interchange type this may be a non-starter, the idea being the user doesn't have to think about anything when passing in say an array into a function - it looks and feels like an overload. I'm not objected to other solutions along these lines though, and I have considered for other things like struct marshalling having marker flags within the pointer types which, when inlined, do the right thing.

One thing we are trying to achieve is near-identical codegen to the user doing all of this themselves. For example, consider [this codegen](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgAYBYAKDIEYbjyACYugOgCUBXAOwwCW+GOwCS/GFAgAHAMqSAbgLAxcAbkYs2XPoOHsAwhHzSBAG0nyoSlepo0BEqADNsK5qIAqME7IzZBMAA1DGAzGgBvGmYY1jokZmxgXAwoNwxWFGZvFIAKAEoNagBfe1pSbJ9pZhAPb19/QJCwyOjYgG0AETMzURNoDFyAIgB9EfEMSV5sMyH8gF02mOIAZjiEmARJqF5MyrzCmlLqRjW+XGxnGFYKzwALRwBzSNil1jX7p+YAeQw7ySKsXezBSUG4YAynGwAHc3lFqECgatmFDoQAqH5/AFvY5Itag8EZAAKqThbzxzGAEAgZg8uAAsthpo8YAATQGI5ZrVEYoIzbgwDmc9r0mB/CCsvrSMy5UXiyUmMzfaSCCC8XDsACCj0esFwuAEChg4jMji+hGYcruEqlSpVAjVGu1utUBqNyr0AgAXgEHbwFuTYsi2AkhNLlAIMjJJAFoMwSVBcjzmGloflmABeAB8zF4MGh8dSzAizD5ZgFmZTMOYxSFiJFYutCulssbNsVHr9Tp1erdxt4pt4TwDCM5wJDzDDprAkeY0bSGDjCdyn14jyraczObzBYTxdL/OuGeYuVTAH4tT0IGAAjACvl2ABxMVlgXfKCdGCubhmQYP1/XLWgYxA28q2q2YEdvajpaj2rqGv2g7Doso6csGWQAGKwDAjLMmyBTAcWhFAgIzgnqIDJMtgLKsvkxGxPCY5McwsjmAA1oyUC4HcMzsFhMB3rkQ78PkAGHKhzG4mOUkxDJzCgU24FWu20qdjBzq9ghJpmmuI4UnumpXjekwERJjFjgo2BQCmYqVkmMJovkrFmBxVncbxhlmNet65AaXowBAzj2Wm4lMbAGBwFmvz/NZx65NFkgXp53kmfkD7PhgAHvp+36/gU7AAXWSIAOy5vmhbWSWFG4dRbKVqkApoAe5ZHjZGRARJxzHKc6w3Cx7Gce54TUOZIHKc2MrjbaanquwAByEDacJjx6UGawTsJGTJcZd6bSC3owOm2bMOQdYKSpk1thNM0agtS3IW8wbxHs/G7Y4GQqlA6YRF1ZRPQk5yXNcZD7BguCtBJXQ9FKAzDF5syrVyvWbNsuzEFkOSDKujxcA5zAIKFryQ1NioQYpUGqrNGnwUa91rswFok6p0FU3B+oIZ2+Der6aqI+Oz3o6DK4PGu7B7gTZISUCmO5AgBWHoTnKkSecvVVRNF0VLDH0TEcuvTVNEFEVsRyXJj3rQLGOqBgqJEhA72SKZQKjYilnWQgdnY7j6L5HQpArMbMQywTdZmxJ/17Jjtv204ADqkZ3LHaTSNIjua87hFu/jnsizjCb5MLTze45fsB4RweKzWRxAA). You can use SharpLab and/or Disasmo in VS to test this.

**Comment by curin** [comment]
> > These types do require a calling convention of being disposed if they are holding a managed object as they keep a pinned GCHandle. The assumption within the generated functions currently is that any Pointer type passed in is either unmanaged or an implicit cast and is disposed at the end of the function. Unmanaged Pointers used in Ptr objects are unaffected by Dispose.
> 
> Oh, I think for an interchange type this may be a non-starter, the idea being the user doesn't have to think about anything when passing in say an array into a function - it looks and feels like an overload. I'm not objected to other solutions along these lines though, and I have considered for other things like struct marshalling having marker flags within the pointer types which, when inlined, do the right thing.
> 
> One thing we are trying to achieve is near-identical codegen to the user doing all of this themselves. For example, consider [this codegen](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgAYBYAKDIEYbjyACYugOgCUBXAOwwCW+GOwCS/GFAgAHAMqSAbgLAxcAbkYs2XPoOHsAwhHzSBAG0nyoSlepo0BEqADNsK5qIAqME7IzZBMAA1DGAzGgBvGmYY1jokZmxgXAwoNwxWFGZvFIAKAEoNagBfe1pSbJ9pZhAPb19/QJCwyOjYgG0AETMzURNoDFyAIgB9EfEMSV5sMyH8gF02mOIAZjiEmARJqF5MyrzCmlLqRjW+XGxnGFYKzwALRwBzSNil1jX7p+YAeQw7ySKsXezBSUG4YAynGwAHc3lFqECgatmFDoQAqH5/AFvY5Itag8EZAAKqThbzxzGAEAgZg8uAAsthpo8YAATQGI5ZrVEYoIzbgwDmc9r0mB/CCsvrSMy5UXiyUmMzfaSCCC8XDsACCj0esFwuAEChg4jMji+hGYcruEqlSpVAjVGu1utUBqNyr0AgAXgEHbwFuTYsi2AkhNLlAIMjJJAFoMwSVBcjzmGloflmABeAB8zF4MGh8dSzAizD5ZgFmZTMOYxSFiJFYutCulssbNsVHr9Tp1erdxt4pt4TwDCM5wJDzDDprAkeY0bSGDjCdyn14jyraczObzBYTxdL/OuGeYuVTAH4tT0IGAAjACvl2ABxMVlgXfKCdGCubhmQYP1/XLWgYxA28q2q2YEdvajpaj2rqGv2g7Doso6csGWQAGKwDAjLMmyBTAcWhFAgIzgnqIDJMtgLKsvkxGxPCY5McwsjmAA1oyUC4HcMzsFhMB3rkQ78PkAGHKhzG4mOUkxDJzCgU24FWu20qdjBzq9ghJpmmuI4UnumpXjekwERJjFjgo2BQCmYqVkmMJovkrFmBxVncbxhlmNet65AaXowBAzj2Wm4lMbAGBwFmvz/NZx65NFkgXp53kmfkD7PhgAHvp+36/gU7AAXWSIAOy5vmhbWSWFG4dRbKVqkApoAe5ZHjZGRARJxzHKc6w3Cx7Gce54TUOZIHKc2MrjbaanquwAByEDacJjx6UGawTsJGTJcZd6bSC3owOm2bMOQdYKSpk1thNM0agtS3IW8wbxHs/G7Y4GQqlA6YRF1ZRPQk5yXNcZD7BguCtBJXQ9FKAzDF5syrVyvWbNsuzEFkOSDKujxcA5zAIKFryQ1NioQYpUGqrNGnwUa91rswFok6p0FU3B+oIZ2+Der6aqI+Oz3o6DK4PGu7B7gTZISUCmO5AgBWHoTnKkSecvVVRNF0VLDH0TEcuvTVNEFEVsRyXJj3rQLGOqBgqJEhA72SKZQKjYilnWQgdnY7j6L5HQpArMbMQywTdZmxJ/17Jjtv204ADqkZ3LHaTSNIjua87hFu/jnsizjCb5MLTze45fsB4RweKzWRxAA). You can use SharpLab and/or Disasmo in VS to test this.

As I mentioned on discord this is actually not for user facing, but for the generated code. It has to dispose of the objects before exiting the function. Sorry that this was not clear.

**Comment by curin** [comment]
Taking into account feedback, I moved the old Mut and Ptr types to be the outermost layer of these generic chains, allowing for us to use the fixed syntax, speeding up our final implementation, but relying on the new types to handle the interior abstractions.

**Comment by curin** [comment]
Closed as this is not currently the intended direction for this feature

**Pull request closed without merging**
